# Generated by Django 4.2.7 on 2023-12-06 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_producto_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_atributo',
            old_name='atributo_id',
            new_name='atributo',
        ),
        migrations.RenameField(
            model_name='producto_atributo',
            old_name='producto_id',
            new_name='producto',
        ),
    ]
