# Generated by Django 4.2.7 on 2023-12-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_atributo_id_producto_atributo_atributo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto_atributo',
            old_name='atributo',
            new_name='atributo_id',
        ),
        migrations.RenameField(
            model_name='producto_atributo',
            old_name='producto',
            new_name='producto_id',
        ),
    ]
